# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzQ3PzC7b9lhaLUFZXFUIdr_dzE_-xot
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

welding_df = pd.read_excel("Welding Data Set_01.xlsx")

welding_df.info()

welding_df.describe() # 최대 최소값을 확인해 이상치가 없는걸로 확인

welding_df.isna().sum()#null값도 없음

welding_df.info()

a = welding_df["working time"]

welding_df

scaled_data = pd.read_csv("scaled_data.csv", encoding="euc-kr")

scaled_data # 스케일러 돌린 독립변수들